// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuntoDeVenta.Infrastructure.Data;

#nullable disable

namespace PuntoDeVenta.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904031820_AddFinanzasYCaja")]
    partial class AddFinanzasYCaja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.Articulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoEstilo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Temporada")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoEstilo")
                        .IsUnique();

                    b.HasIndex("MarcaId");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.VarianteArticulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PermiteDescuentoMedioPago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioLista")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecioOferta")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasFilter("CodigoBarras IS NOT NULL AND CodigoBarras <> ''");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("VariantesArticulo");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Finanzas.CategoriaGasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsGastoPersonal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoGasto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasGasto");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Finanzas.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Canal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CategoriaGastoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPersonal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TurnoCajaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("TurnoCajaId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Finanzas.MovimientoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Canal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Concepto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaComprobante")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TurnoCajaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TurnoCajaId");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Finanzas.TurnoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoInicialEfectivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoRealEfectivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoRealTarjetas")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoRealTransferencias")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoTeoricoEfectivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoTeoricoTarjetas")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoTeoricoTransferencias")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionesApertura")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioApertura")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCierre")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TurnosCaja");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Inventario.MovimientoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockPrevio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockResultante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VarianteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VarianteId");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Ventas.LineaVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoUnitarioHistorico")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionArticulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DescuentoMedioPagoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DescuentoOfertaUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioFinalCobrado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioListaUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RecargoMedioPagoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VarianteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VarianteId");

                    b.ToTable("LineasVenta");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Ventas.MetodoPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ComisionPorcentual")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlazoAcreditacionDias")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeAjuste")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.Articulo", b =>
                {
                    b.HasOne("PuntoDeVenta.Domain.Entities.Catalogo.Categoria", "Categoria")
                        .WithMany("Articulos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PuntoDeVenta.Domain.Entities.Catalogo.Marca", "Marca")
                        .WithMany("Articulos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.VarianteArticulo", b =>
                {
                    b.HasOne("PuntoDeVenta.Domain.Entities.Catalogo.Articulo", "Articulo")
                        .WithMany("Variantes")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Finanzas.Gasto", b =>
                {
                    b.HasOne("PuntoDeVenta.Domain.Entities.Finanzas.CategoriaGasto", "CategoriaGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaGastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PuntoDeVenta.Domain.Entities.Finanzas.TurnoCaja", "TurnoCaja")
                        .WithMany("Gastos")
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaGasto");

                    b.Navigation("TurnoCaja");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Finanzas.MovimientoCaja", b =>
                {
                    b.HasOne("PuntoDeVenta.Domain.Entities.Finanzas.TurnoCaja", "TurnoCaja")
                        .WithMany("Movimientos")
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TurnoCaja");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Inventario.MovimientoStock", b =>
                {
                    b.HasOne("PuntoDeVenta.Domain.Entities.Catalogo.VarianteArticulo", "Variante")
                        .WithMany()
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Ventas.LineaVenta", b =>
                {
                    b.HasOne("PuntoDeVenta.Domain.Entities.Catalogo.VarianteArticulo", "Variante")
                        .WithMany()
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.Articulo", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Catalogo.Marca", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Finanzas.CategoriaGasto", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("PuntoDeVenta.Domain.Entities.Finanzas.TurnoCaja", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
