<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PuntoDeVenta.Infrastructure\PuntoDeVenta.Infrastructure.csproj" />
    <ProjectReference Include="..\PuntoDeVenta.Application\PuntoDeVenta.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\mr_sys_icon.ico</ApplicationIcon>
    <AssemblyTitle>MR SYS Retail</AssemblyTitle>
    <Product>MR SYS Retail - Terminal POS</Product>
    <Company>MR SYS</Company>
    <Copyright>© 2026 MR SYS. Todos los derechos reservados.</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\mr_sys_icon.ico" />
  </ItemGroup>
</Project>
